#!/usr/bin/env python3
"""Build js/us-cities.js from the public US cities gazetteer."""

import csv
import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path("/tmp/us_cities.csv")
OUT = ROOT / "js" / "us-cities.js"


def norm(name: str) -> str:
    text = name.lower().strip()
    text = text.replace(".", "").replace("'", "").replace("’", "")
    text = re.sub(r"\s+", " ", text)
    return text


def main() -> None:
    grouped = defaultdict(list)
    with SRC.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            state = (row.get("STATE_CODE") or "").strip().lower()
            city = norm(row.get("CITY") or "")
            try:
                lat = float(row["LATITUDE"])
                lon = float(row["LONGITUDE"])
            except (KeyError, TypeError, ValueError):
                continue
            if not state or not city:
                continue
            grouped[(state, city)].append((lon, lat))

    payload = {}
    for (state, city), points in grouped.items():
        lon = sum(p[0] for p in points) / len(points)
        lat = sum(p[1] for p in points) / len(points)
        payload.setdefault(state, {})[city] = [round(lon, 4), round(lat, 4)]

    body = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    OUT.write_text(
        "// Generated by scripts/generate-us-cities.py — city lon/lat for map pins.\n"
        f"window.US_CITY_COORDS = {body};\n",
        encoding="utf-8",
    )
    count = sum(len(cities) for cities in payload.values())
    print(f"Wrote {OUT} ({count} cities, {OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
